/// <reference types="react" />
declare const _default: {
    Button: import("react").ForwardRefExoticComponent<import("./components/atoms/Button/Component").ButtonProps & import("react").RefAttributes<import("react-native").TouchableOpacity>>;
    Image: import("react").ForwardRefExoticComponent<Pick<import("./components/atoms/Image/Component").ImageProps, "style" | "onLayout" | "testID" | "nativeID" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityRole" | "accessibilityState" | "accessibilityHint" | "accessibilityValue" | "onAccessibilityAction" | "accessibilityLiveRegion" | "importantForAccessibility" | "accessibilityElementsHidden" | "accessibilityViewIsModal" | "onAccessibilityEscape" | "onAccessibilityTap" | "onMagicTap" | "accessibilityIgnoresInvertColors" | "source" | "borderBottomLeftRadius" | "borderBottomRightRadius" | "borderRadius" | "borderTopLeftRadius" | "borderTopRightRadius" | "onError" | "onLoad" | "onLoadEnd" | "onLoadStart" | "progressiveRenderingEnabled" | "resizeMode" | "resizeMethod" | "loadingIndicatorSource" | "defaultSource" | "blurRadius" | "capInsets" | "onProgress" | "onPartialLoad" | "fadeDuration" | "ImageComponent" | "uri"> & import("react").RefAttributes<import("react-native").Image>>;
    Input: import("react").ForwardRefExoticComponent<import("./components/atoms/Input/Component").InputProps & import("react").RefAttributes<import("react-native").View>>;
    Text: import("react").ForwardRefExoticComponent<import("./components/atoms/Text/Component").TextProps & import("react").RefAttributes<import("react-native").Text>>;
    Page: import("react").ForwardRefExoticComponent<import("./components/atoms/Page/Component").PageProps & import("react").RefAttributes<import("react-native").View | import("react-native").KeyboardAvoidingView>>;
    View: import("react").ForwardRefExoticComponent<import("./components/atoms/View/Component").ViewProps & import("react").RefAttributes<import("react-native").View>>;
    ScrollView: import("react").ForwardRefExoticComponent<import("./components/atoms/ScrollView/Component").ScrollViewProps & import("react").RefAttributes<import("react-native").ScrollView>>;
    Icon: import("react").ForwardRefExoticComponent<import("./components/atoms/Icon/Component").IconProps & import("react").RefAttributes<import("react-native").View>>;
    Header: import("react").ForwardRefExoticComponent<import("./components/atoms/Header/Component").HeaderProps & import("react").RefAttributes<import("react-native").View>>;
    OTPInput: import("react").ForwardRefExoticComponent<Pick<import("./components/atoms/OTPInput/Component").OTPInputProps, "style" | "children" | "allowFontScaling" | "numberOfLines" | "onLayout" | "onPressIn" | "onPressOut" | "testID" | "nativeID" | "maxFontSizeMultiplier" | "selectionColor" | "textBreakStrategy" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityRole" | "accessibilityState" | "accessibilityHint" | "accessibilityValue" | "onAccessibilityAction" | "accessibilityLiveRegion" | "importantForAccessibility" | "accessibilityElementsHidden" | "accessibilityViewIsModal" | "onAccessibilityEscape" | "onAccessibilityTap" | "onMagicTap" | "accessibilityIgnoresInvertColors" | "textAlign" | "hitSlop" | "pointerEvents" | "removeClippedSubviews" | "collapsable" | "needsOffscreenAlphaCompositing" | "renderToHardwareTextureAndroid" | "focusable" | "shouldRasterizeIOS" | "isTVSelectable" | "hasTVPreferredFocus" | "tvParallaxProperties" | "tvParallaxShiftDistanceX" | "tvParallaxShiftDistanceY" | "tvParallaxTiltAngle" | "tvParallaxMagnification" | "onStartShouldSetResponder" | "onMoveShouldSetResponder" | "onResponderEnd" | "onResponderGrant" | "onResponderReject" | "onResponderMove" | "onResponderRelease" | "onResponderStart" | "onResponderTerminationRequest" | "onResponderTerminate" | "onStartShouldSetResponderCapture" | "onMoveShouldSetResponderCapture" | "onTouchStart" | "onTouchMove" | "onTouchEnd" | "onTouchCancel" | "onTouchEndCapture" | "key" | "onBlur" | "onFocus" | "value" | "defaultValue" | "autoFocus" | "autoComplete" | "maxLength" | "onChangeText" | "onChange" | "multiline" | "autoCapitalize" | "autoCorrect" | "blurOnSubmit" | "caretHidden" | "contextMenuHidden" | "editable" | "keyboardType" | "onContentSizeChange" | "onEndEditing" | "onSelectionChange" | "onSubmitEditing" | "onTextInput" | "onScroll" | "onKeyPress" | "placeholder" | "placeholderTextColor" | "returnKeyType" | "secureTextEntry" | "selectTextOnFocus" | "selection" | "inputAccessoryViewID" | "clearButtonMode" | "clearTextOnFocus" | "dataDetectorTypes" | "enablesReturnKeyAutomatically" | "keyboardAppearance" | "passwordRules" | "rejectResponderTermination" | "selectionState" | "spellCheck" | "textContentType" | "scrollEnabled" | "importantForAutofill" | "disableFullscreenUI" | "inlineImageLeft" | "inlineImagePadding" | "returnKeyLabel" | "underlineColorAndroid" | "textAlignVertical" | "showSoftInputOnFocus" | "errorMessage" | "isPreview" | "renderCell" | "RootProps" | "RootComponent" | "rootStyle" | "textInputStyle" | "cellCount" | "pinCount" | "cellStyle" | "focusCellStyle" | "cellTextStyle" | "focusCellTextStyle" | "otpInputType" | "isSecure" | "onCodeChanged" | "errorProps" | "renderErrorMessage" | "errorStyle"> & import("react").RefAttributes<import("react-native").View>>;
    Divider: import("react").ForwardRefExoticComponent<import("./components/atoms/Divider/Component").DividerProps & import("react").RefAttributes<import("react-native").View>>;
    WebView: import("react").ForwardRefExoticComponent<import("./components/atoms/WebView/Component").WebViewProps & import("react").RefAttributes<import("react-native-webview").WebView<{}>>>;
    ImagePicker: import("react").ForwardRefExoticComponent<import("./components/atoms/ImagePicker/Component").ImagePickerProps & import("react").RefAttributes<import("react-native").View>>;
    Carousel: import("react").ForwardRefExoticComponent<import("./components/molecules/Carousel/Component").CarouselProps & import("react").RefAttributes<import("react-native").View>>;
    DatePicker: import("react").ForwardRefExoticComponent<import("./components/atoms/DatePicker/Component").DatePickerProps & import("react").RefAttributes<import("react-native").TouchableOpacity>>;
    FlatList: import("react").ForwardRefExoticComponent<import("./components/molecules/FlatList/Component").FlatListProps & import("react").RefAttributes<import("react-native").View | import("react-native").FlatList<unknown>>>;
    TouchableOpacity: import("react").ForwardRefExoticComponent<import("./components/atoms/TouchableOpacity/Component").TouchableOpacityProps & import("react").RefAttributes<import("react-native").TouchableOpacity>>;
};
export default _default;
